PORT = 35000
SERVER_ADDRESS = "localhost"
LOG_FILENAME = "server.log"
LOG_LEVEL = 1
COMMAND_SIZE = 9
MAX_STR_SIZE = 20
INT_SIZE = 8
QUADX_OP = "quad_x   "
QUADY_OP = "quad_y   "

CHECK_PATH_OP = "check    "
CHECK_BOOST_OP = "chboost  "
POS_BOOS_OP = "pboost   "
PLAYER_OP = "player   "
GET_WORLD_OP = "world    "
START_GAME ="game     "
READY_PLAYER ="ready    "
GAME_OVER = "gover    "
CHECK_GAME_OVER = "cgover   "
RESET_GAMEMECH = "reset_gm "
UPDATE_OP = "update   "
BYE_OP = "bye      "  #os espacos depois do que está escrito estao errados e é preciso meter certo
STOP_SERVER_OP = "stop     "
NR_QUAD_x = 70
NR_QUAD_Y = 35
NR_CLIENTS = 2
